lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "frick_llvm_ext"
rust-version.workspace = true
version.workspace = true

[dependencies]
libc.workspace = true
llvm-sys.workspace = true

[build-dependencies]
cc = "1"
build-rs = "0.3"
