lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "frick_instructions"
rust-version.workspace = true
version.workspace = true

[dependencies]
frick_operations.workspace = true
