lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "frick_types"
rust-version.workspace = true
version.workspace = true

[dependencies]
frick_spec.workspace = true
serde = { workspace = true, default-features = false, features = ["derive"] }
