lints.workspace = true

[package]
edition.workspace = true
license.workspace = true
name = "frick_interop"
rust-version.workspace = true
version.workspace = true

[dependencies]
libc.workspace = true
crossterm = "0.29"
